### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @cclauss! I've created [OSPR-3227](https://openedx.atlassian.net/browse/OSPR-3227) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by cclauss** [comment]
Closing in favor of #66

**Comment by edx-webhook** [comment]
@cclauss Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/codejail&entry.867055334=https://github.com/edx/codejail/pull/65&entry.1484655318=https://github.com/cclauss&entry.752974735=2019-03-19+21:44&entry.1917517419=2019-03-19+22:36&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@cclauss Thank you for your attempt to contribute.

**Pull request closed without merging**
