### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by AdityaOli**
Corrected the spelling from 'execution' to 'execute'.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @AdityaOli! I've created [OSPR-1599](https://openedx.atlassian.net/browse/OSPR-1599) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/codejail/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@AdityaOli Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but you only have to do this *once* and we're hoping you would make future contributions as well.

**Comment by AdityaOli** [comment]
Do i have to print->fill->scan and then upload it again?


Thanks and Regards,

[image: Picture]
Aditya Oli
Python Programming Geek & Knowledge Enthusiast

m:
e: adityaoligehu@gmail.com

<https://www.facebook.com/eradityaoli>
<https://in.linkedin.com/in/eradityaoli>


*"Everybody in this country should learn to program a computer... because
it teaches you how to think."*
*-Steve Jobs*

**Comment by gsong** [comment]
@AdityaOli When did you send it in to legal? I can follow up on this end.

**Pull request merged**
